name: End-to-end tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Copying the Project
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Start Serverest Service
        run: npm run serverest:start &
        env:
          CI: true

      - name: Wait for Serverest to be ready
        run: |
          echo "Waiting for Serverest to be ready..."
          timeout 30s bash -c 'until curl -s http://localhost:3000/ > /dev/null; do sleep 1; done'
          echo "Serverest is ready!"

      - name: Run Cypress Tests in Cloud
        run: npm run test:cloud
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Upload screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload videos if successful
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
